# Replace each "{SELF}" with your chosen name.  Then deploy via
#     kubectl apply -f workload.yaml
# This will create NEGs that you can later re-use with your real workload.
# This workload simply always gives a 403 HTTP response.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {SELF}
  namespace: default
  labels:
    app: {SELF}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {SELF}
  template:
    metadata:
      labels:
        app: {SELF}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: {SELF}
          image: tyemcq/http-rejector:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              cpu: 8m
              memory: 8Mi

---
kind: Service
apiVersion: v1
metadata:
  name: {SELF}
  namespace: default
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"{SELF}"}}}'
  labels:
    app: {SELF}
spec:
  type: NodePort
  selector:
    app: {SELF}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
